# Generated by Django 4.2.4 on 2023-08-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created_data',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated_data',
        ),
    ]
