# Generated by Django 4.2.4 on 2023-08-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_created_at_product_created_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('категория товара',)},
        ),
    ]
